variable checks

diff --git a/.github/workflows/build-deploy-test.yml b/.github/workflows/build-deploy-test.yml
--- a/.github/workflows/build-deploy-test.yml
+++ b/.github/workflows/build-deploy-test.yml
@@ -16,6 +16,39 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
+      - name: Check Required Variables
+        shell: bash
+        run: |
+          declare -A REQUIRED_VARS=(
+            ["CI"]="false"
+            ["NODE_ENV"]="development"
+            ["PORT"]="3000"
+            ["REACT_APP_NAME"]="Food Club Adda"
+            ["REACT_APP_DESCRIPTION"]="A modern pizza ordering application"
+            ["REACT_APP_VERSION"]="'1.0.0'"
+            ["REACT_APP_PRICE"]="500"
+            ["REACT_APP_BUTTON_TITLE"]="Add to Favorites"
+            ["REACT_APP_PIZZA_DESCRIPTION"]="This delicious dish is easy to make and packed with flavor."
+            ["REACT_APP_API_URL"]="https://api.pizza.com/v1"
+            ["REACT_APP_API_KEY"]="1234567890abcdef1234567890abcdef"
+            ["REACT_APP_API_TIMEOUT"]="5000"
+            ["REACT_APP_ANALYTICS_ID"]="G-1A2B3C4D5E"
+            ["REACT_APP_ENABLE_ERROR_REPORTING"]=""
+            ["REACT_APP_SOCIAL_SHARING_URL"]="https://sumit007521.github.io/"
+          )
+          check_exit_status=0
+          for ITEM in "${!REQUIRED_VARS[@]}"; 
+          do
+            if [ -z "${REQUIRED_VARS[${ITEM}]}" ]; then
+              echo "Error: Environment variable '$ITEM' is not set."
+              check_exit_status=1
+            fi
+            else
+                echo "Environment variable '$ITEM' is set to '${REQUIRED_VARS[${ITEM}]}'"
+            fi    
+          done 
+          exit $check_exit_status 
+
       - name: Setup Node.js
         uses: actions/setup-node@v4
         with:
