custom action check var

diff --git a/.github/workflows/deploy-with-action.yml b/.github/workflows/deploy-with-action.yml
--- a/.github/workflows/deploy-with-action.yml
+++ b/.github/workflows/deploy-with-action.yml
@@ -19,7 +19,6 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      # 🧩 Your Custom Action replaces manual env blocks
       - name: Get environment variables
         uses: Sumit007521/getEnvVars@feature/update
         with:
@@ -27,6 +26,38 @@ jobs:
             gh_token: ${{ vars.GH_TOKEN }}
 
 
+      - name: Check Required Variables
+        shell: bash
+        run: |
+          declare -A REQUIRED_VARS=(
+            ["CI"]=${{ vars.CI }}
+            ["NODE_ENV"]=${{ vars.NODE_ENV }}
+            ["PORT"]=${{ vars.PORT }}
+            ["REACT_APP_NAME"]=${{ vars.REACT_APP_NAME }}
+            ["REACT_APP_DESCRIPTION"]=${{ vars.REACT_APP_DESCRIPTION }}
+            ["REACT_APP_VERSION"]=${{ vars.REACT_APP_VERSION }}
+            ["REACT_APP_PRICE"]=${{ vars.REACT_APP_PRICE }}
+            ["REACT_APP_BUTTON_TITLE"]=${{ vars.REACT_APP_BUTTON_TITLE }}
+            ["REACT_APP_PIZZA_DESCRIPTION"]=${{ vars.REACT_APP_PIZZA_DESCRIPTION }}
+            ["REACT_APP_API_URL"]=${{ vars.REACT_APP_API_URL }}
+            ["REACT_APP_API_KEY"]=${{ vars.REACT_APP_API_KEY }}
+            ["REACT_APP_API_TIMEOUT"]=${{ vars.REACT_APP_API_TIMEOUT }}
+            ["REACT_APP_ANALYTICS_ID"]=${{ vars.REACT_APP_ANALYTICS_ID }}
+            ["REACT_APP_ENABLE_ERROR_REPORTING"]=${{ vars.REACT_APP_ENABLE_ERROR_REPORTING }}
+            ["REACT_APP_SOCIAL_SHARING_URL"]=${{ vars.REACT_APP_SOCIAL_SHARING_URL }}
+          )
+          check_exit_status=0
+          for ITEM in "${!REQUIRED_VARS[@]}"; 
+          do
+            if [ -z "${REQUIRED_VARS[${ITEM}]}" ]; then
+              echo "Error: Environment variable '$ITEM' is not set."
+              check_exit_status=1
+            else
+                echo "Environment variable '$ITEM' is set to '${REQUIRED_VARS[${ITEM}]}'"
+            fi    
+          done 
+          exit $check_exit_status
+            
       - name: Setup Node.js
         uses: actions/setup-node@v4
         with:
